#FROM gocd/gocd-agent-centos-9:v22.3.0
FROM gocd/gocd-agent-alpine-3.16:v22.3.0
USER root
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
ENTRYPOINT ["/docker-entrypoint.sh"]
USER go
