gitea:
  admin:
    username: gitea-admin
    password: admin
  config:
    metrics: 
      ENABLED: true
    server:
      DOMAIN: gunsmoke.local
      ROOT_URL: http://gitea.gunsmoke.local:9080/
service:
  http:
    serviceType: ClusterIP
    port: 3000
    externalPort: 9080
    externalHost: gitea.gunsmoke.local
  ssh:
    serviceType: NodePort
    port: 22
    externalPort: 8022
    externalHost: gitea.gunsmoke.local
