gitea:
  admin:
    username: gitea-admin
    password: admin
  config:
    metrics: 
      ENABLED: true
server:
  DOMAIN: gunsmoke
  ROOT_URL: http://gunsmoke
service:
  http:
    serviceType: ClusterIP
    port: 3000
    externalPort: 8280
    externalHost: gunsmoke
  ssh:
    serviceType: NodePort
    port: 22
    externalPort: 8022
    externalHost: gunsmoke
