kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: gocd-agent-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gocd-agent-rolebinding
  namespace: default
subjects:
- kind: User
  name: system:serviceaccount:gocd:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: gocd-agent-role
  apiGroup: rbac.authorization.k8s.io
