apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ping
  labels:
    name: ping
spec:
  selector:
    matchLabels:
      app: ping
  endpoints:
    - port: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pong
  labels:
    name: pong
spec:
  selector:
    matchLabels:
      app: pong
  endpoints:
    - port: http
