apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
  labels:
    app: ping
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
      version: v1
  template:
    metadata:
      labels:
        app: ping
        version: v1
    spec:
      containers:
      - name: ping
        #image: k3d-myregistry.localhost:12345/ping:v1
        image: jstrohm/ping:50
      imagePullSecrets:
      - name: regcred
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#name: gateway-ping
#annotations:
#kubernetes.io/ingress.class: "istio"
#spec:
#rules:
#- http:
#paths:
#- path: /
#pathType: Prefix
#backend:
#service:
#name: ping
#port:
#number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ping
  labels:
    app: ping
    service: ping
spec:
  selector:
    app: ping
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ping-sm
  labels:
    name: ping
spec:
  selector:
    matchLabels:
      app: ping
  endpoints:
    - port: http
      path: /metrics
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ping
spec:
  hosts:
  - ping.gunsmoke.local
  gateways:
  - default/primary-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    - port: 8080
    route:
    - destination:
        host: ping.default.svc.cluster.local
        port:
          number: 8080
      weight: 100
