apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
  labels:
    app: pong
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
      version: v1
  template:
    metadata:
      labels:
        app: pong
        version: v1
    spec:
      containers:
      - name: pong
        #image: k3d-myregistry.localhost:12345/p.ng:v1
        image: jstrohm/pong:34
      imagePullSecrets:
      - name: regcred
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#name: gateway-pong
#annotations:
#kubernetes.io/ingress.class: "istio"
#spec:
#rules:
#- http:
#paths:
#- path: /
#pathType: Prefix
#backend:
#service:
#name: pong
#port:
#number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pong
  labels:
    app: pong
    service: pong
spec:
  selector:
    app: pong
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pong-sm
  labels:
    name: pong
spec:
  selector:
    matchLabels:
      app: pong
  endpoints:
    - port: http
      path: /metrics
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pong
spec:
  hosts:
  - pong.gunsmoke.local
  gateways:
  - default/primary-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    - port: 8080
    route:
    - destination:
        host: pong.default.svc.cluster.local
        port:
          number: 8080
      weight: 100
