format_version: 10
pipelines:
  pong:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-589ea36:
        git: https://github.com/hoyle1974/synthetic_infra.git
        shallow_clone: false
        auto_update: true
        branch: main
      upstream:
        pipeline: pingpong
        stage: compile
    stages:
    - package:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          package-pong:
            elastic_profile_id: buildah
            timeout: 0
            artifacts:
            - build:
                source: build
            tasks:
            - fetch:
                pipeline: pingpong
                stage: compile
                job: compile-pingpong
                source: bin/
            - exec:
                arguments:
                  - -c
                  - pwd
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - find .
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - find /go/pipelines
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - buildah bud -t pong:${GO_PIPELINE_LABEL} -f Dockerfile.pong .
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - mkdir build && cd build && buildah push pong:${GO_PIPELINE_LABEL} oci-archive:./pong.tar:pong:${GO_PIPELINE_LABEL}
                command: /bin/bash
                run_if: passed
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy-pong:
            elastic_profile_id: buildah
            timeout: 0
            artifacts:
            tasks:
            - fetch:
                pipeline: pong
                stage: package
                job: package-pong
                source: build/
            - exec:
                arguments:
                  - -c
                  - buildah pull oci-archive:./build/pong.tar 
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - buildah login -u jstrohm -p ${DOCKER_PASSWORD} docker.io
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - buildah push pong:${GO_PIPELINE_LABEL} docker://jstrohm/pong:${GO_PIPELINE_LABEL}
                command: /bin/bash
                run_if: passed
