format_version: 10
pipelines:
  synthetic-infra-ping:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-589ea36:
        git: https://github.com/hoyle1974/synthetic_infra.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build-ping:
            elastic_profile_id: buildah
            timeout: 0
            artifacts:
            - build:
                source: build
            tasks:
            - exec:
                arguments:
                  - -c
                  - buildah bud -t ping:${GO_PIPELINE_LABEL} -f Dockerfile.ping .
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - mkdir build && cd build && buildah push ping:${GO_PIPELINE_LABEL} oci-archive:./ping.tar:ping:${GO_PIPELINE_LABEL}
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - find /godata/pipelines/synthetic-infra-ping
                command: /bin/bash
                run_if: passed
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build-ping:
            elastic_profile_id: buildah
            timeout: 0
            artifacts:
            tasks:
            - fetch:
                pipeline: synthetic-infra-ping
                stage: build
                job: build-ping
                source: build/
            - exec:
                arguments:
                  - -c
                  - buildah pull oci-archive:./build/ping.tar 
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - buildah images
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - buildah login -u jstrohm -p ${DOCKER_PASSWORD} docker.io
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - buildah push ping:${GO_PIPELINE_LABEL} docker://jstrohm/ping:${GO_PIPELINE_LABEL}
                command: /bin/bash
                run_if: passed
